//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from LuceneParser.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="LuceneParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.CLSCompliant(false)]
public interface ILuceneParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuceneParser.topLevelQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTopLevelQuery([NotNull] LuceneParser.TopLevelQueryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuceneParser.query"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuery([NotNull] LuceneParser.QueryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuceneParser.disjQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDisjQuery([NotNull] LuceneParser.DisjQueryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuceneParser.conjQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConjQuery([NotNull] LuceneParser.ConjQueryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuceneParser.modClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModClause([NotNull] LuceneParser.ModClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuceneParser.modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModifier([NotNull] LuceneParser.ModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuceneParser.clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClause([NotNull] LuceneParser.ClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuceneParser.fieldRangeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldRangeExpr([NotNull] LuceneParser.FieldRangeExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuceneParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm([NotNull] LuceneParser.TermContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuceneParser.groupingExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroupingExpr([NotNull] LuceneParser.GroupingExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuceneParser.fieldName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldName([NotNull] LuceneParser.FieldNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuceneParser.termRangeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTermRangeExpr([NotNull] LuceneParser.TermRangeExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuceneParser.quotedTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuotedTerm([NotNull] LuceneParser.QuotedTermContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LuceneParser.fuzzy"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuzzy([NotNull] LuceneParser.FuzzyContext context);
}
