//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from LuceneParser.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="LuceneParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.CLSCompliant(false)]
public interface ILuceneParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuceneParser.topLevelQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTopLevelQuery([NotNull] LuceneParser.TopLevelQueryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuceneParser.topLevelQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTopLevelQuery([NotNull] LuceneParser.TopLevelQueryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuceneParser.query"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuery([NotNull] LuceneParser.QueryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuceneParser.query"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuery([NotNull] LuceneParser.QueryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuceneParser.disjQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDisjQuery([NotNull] LuceneParser.DisjQueryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuceneParser.disjQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDisjQuery([NotNull] LuceneParser.DisjQueryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuceneParser.conjQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConjQuery([NotNull] LuceneParser.ConjQueryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuceneParser.conjQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConjQuery([NotNull] LuceneParser.ConjQueryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuceneParser.modClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModClause([NotNull] LuceneParser.ModClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuceneParser.modClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModClause([NotNull] LuceneParser.ModClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuceneParser.modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModifier([NotNull] LuceneParser.ModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuceneParser.modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModifier([NotNull] LuceneParser.ModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuceneParser.clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClause([NotNull] LuceneParser.ClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuceneParser.clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClause([NotNull] LuceneParser.ClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuceneParser.fieldRangeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldRangeExpr([NotNull] LuceneParser.FieldRangeExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuceneParser.fieldRangeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldRangeExpr([NotNull] LuceneParser.FieldRangeExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuceneParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerm([NotNull] LuceneParser.TermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuceneParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerm([NotNull] LuceneParser.TermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuceneParser.groupingExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGroupingExpr([NotNull] LuceneParser.GroupingExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuceneParser.groupingExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGroupingExpr([NotNull] LuceneParser.GroupingExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuceneParser.fieldName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldName([NotNull] LuceneParser.FieldNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuceneParser.fieldName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldName([NotNull] LuceneParser.FieldNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuceneParser.termRangeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTermRangeExpr([NotNull] LuceneParser.TermRangeExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuceneParser.termRangeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTermRangeExpr([NotNull] LuceneParser.TermRangeExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuceneParser.quotedTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuotedTerm([NotNull] LuceneParser.QuotedTermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuceneParser.quotedTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuotedTerm([NotNull] LuceneParser.QuotedTermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuceneParser.fuzzy"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuzzy([NotNull] LuceneParser.FuzzyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuceneParser.fuzzy"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuzzy([NotNull] LuceneParser.FuzzyContext context);
}
